// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env["WEB_API_KEY"]!,
    appId: '1:213617117395:web:25114c10de5fd578ad6c26',
    messagingSenderId: '213617117395',
    projectId: 'tik-tok-52296',
    authDomain: 'tik-tok-52296.firebaseapp.com',
    storageBucket: 'tik-tok-52296.appspot.com',
    measurementId: 'G-C20Y6S2QZX',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env["ANDROID_API_KEY"]!,
    appId: '1:213617117395:android:24b1a204c55b5ee4ad6c26',
    messagingSenderId: '213617117395',
    projectId: 'tik-tok-52296',
    storageBucket: 'tik-tok-52296.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env["IOS_API_KEY"]!,
    appId: '1:213617117395:ios:cdb766a17ab7415aad6c26',
    messagingSenderId: '213617117395',
    projectId: 'tik-tok-52296',
    storageBucket: 'tik-tok-52296.appspot.com',
    iosBundleId: 'com.example.kyumjaeTikTokCloneTest1',
  );
}
